<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\TerrariaSeedRoller.Core\TerrariaSeedRoller.Core.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>1.2.0</Version>
    <AssemblyName>TerrariaSeedRoller.Cli</AssemblyName>
  </PropertyGroup>

</Project>
