# Converts the Lucide SVG icon set into a generated C# path-data table.
# Lucide artwork is ISC licensed (https://lucide.dev). Primitives (circle, rect,
# line, polyline, polygon, ellipse) are normalised to SVG path data so the
# runtime only needs a single path grammar.
[CmdletBinding()]
param(
    [string]$IconDir,
    [string]$Output
)

$ErrorActionPreference = 'Stop'
$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
if (-not $IconDir) { $IconDir = Join-Path $scriptDir 'icons' }
if (-not $Output) { $Output = Join-Path $scriptDir '..\src\TerrariaSeedRoller.App\Design\IconData.cs' }
$inv = [System.Globalization.CultureInfo]::InvariantCulture
function N([double]$v) { $v.ToString('0.####', $inv) }

function Convert-Rect($e) {
    $x = [double]$e.x; $y = [double]$e.y; $w = [double]$e.width; $h = [double]$e.height
    $rx = 0.0; if ($e.rx) { $rx = [double]$e.rx }
    if ($rx -le 0) {
        return "M$(N $x) $(N $y)h$(N $w)v$(N $h)h$(-(N $w))Z"
    }
    $ry = $rx; if ($e.ry) { $ry = [double]$e.ry }
    $x1 = $x + $w; $y1 = $y + $h
    return "M$(N ($x + $rx)) $(N $y)h$(N ($w - 2 * $rx))a$(N $rx) $(N $ry) 0 0 1 $(N $rx) $(N $ry)v$(N ($h - 2 * $ry))a$(N $rx) $(N $ry) 0 0 1 $(-(N $rx)) $(N $ry)h$(-(N ($w - 2 * $rx)))a$(N $rx) $(N $ry) 0 0 1 $(-(N $rx)) $(-(N $ry))v$(-(N ($h - 2 * $ry)))a$(N $rx) $(N $ry) 0 0 1 $(N $rx) $(-(N $ry))Z"
}

function Convert-Ellipse($cx, $cy, $rx, $ry) {
    $cx = [double]$cx; $cy = [double]$cy; $rx = [double]$rx; $ry = [double]$ry
    return "M$(N ($cx - $rx)) $(N $cy)a$(N $rx) $(N $ry) 0 1 0 $(N (2 * $rx)) 0a$(N $rx) $(N $ry) 0 1 0 $(-(N (2 * $rx))) 0Z"
}

function Convert-Points($points, [bool]$close) {
    $nums = [regex]::Matches($points, '-?\d*\.?\d+(?:e-?\d+)?') | ForEach-Object { [double]$_.Value }
    if ($nums.Count -lt 4) { return $null }
    $sb = New-Object System.Text.StringBuilder
    [void]$sb.Append("M$(N $nums[0]) $(N $nums[1])")
    for ($i = 2; $i + 1 -lt $nums.Count; $i += 2) { [void]$sb.Append("L$(N $nums[$i]) $(N $nums[$i + 1])") }
    if ($close) { [void]$sb.Append('Z') }
    return $sb.ToString()
}

$files = Get-ChildItem -LiteralPath $IconDir -Filter *.svg | Sort-Object Name
if ($files.Count -eq 0) { throw "No SVG files found in $IconDir" }
$version = 'unknown'
$versionFile = Join-Path $IconDir 'VERSION.txt'
if (Test-Path -LiteralPath $versionFile) { $version = (Get-Content -LiteralPath $versionFile -Raw).Trim() }

$entries = New-Object System.Collections.Generic.List[string]
foreach ($f in $files) {
    $name = [IO.Path]::GetFileNameWithoutExtension($f.Name)
    [xml]$svg = Get-Content -LiteralPath $f.FullName -Raw
    $parts = New-Object System.Collections.Generic.List[string]
    foreach ($node in $svg.svg.ChildNodes) {
        if ($node.NodeType -ne 'Element') { continue }
        switch ($node.LocalName) {
            'path'    { if ($node.d) { $parts.Add(($node.d -replace '\s+', ' ').Trim()) } }
            'circle'  { $parts.Add((Convert-Ellipse $node.cx $node.cy $node.r $node.r)) }
            'ellipse' { $parts.Add((Convert-Ellipse $node.cx $node.cy $node.rx $node.ry)) }
            'rect'    { $parts.Add((Convert-Rect $node)) }
            'line'    { $parts.Add("M$($node.x1) $($node.y1)L$($node.x2) $($node.y2)") }
            'polyline'{ $p = Convert-Points $node.points $false; if ($p) { $parts.Add($p) } }
            'polygon' { $p = Convert-Points $node.points $true; if ($p) { $parts.Add($p) } }
            default   { Write-Warning "Unhandled element <$($node.LocalName)> in $name" }
        }
    }
    if ($parts.Count -eq 0) { throw "Icon '$name' produced no artwork." }
    $literals = ($parts | ForEach-Object { '"' + ($_ -replace '\\', '\\' -replace '"', '\"') + '"' }) -join ', '
    $entries.Add("        [""$name""] = [$literals],")
}

$header = @"
// <auto-generated />
// Icon artwork derived from Lucide v$version (https://lucide.dev), ISC License.
// Primitives were normalised to SVG path data; see scripts/generate-icons.ps1.
// Regenerate with:  powershell -ExecutionPolicy Bypass -File scripts/generate-icons.ps1

namespace TerrariaSeedRoller.App.Design;

/// <summary>Raw 24x24 stroke artwork for every icon shipped with the application.</summary>
internal static class IconData
{
    public static readonly IReadOnlyDictionary<string, string[]> Artwork =
        new Dictionary<string, string[]>(StringComparer.Ordinal)
        {
$($entries -join "`r`n")
        };
}
"@

$full = [IO.Path]::GetFullPath($Output)
New-Item -ItemType Directory -Path ([IO.Path]::GetDirectoryName($full)) -Force | Out-Null
[IO.File]::WriteAllText($full, $header, (New-Object System.Text.UTF8Encoding($false)))
Write-Host "Generated $full with $($entries.Count) icons (lucide v$version)."
